### ISSUE TITLE
Write time-sorted record of each deployment

### ISSUE THREAD

**Issue by lukebond** [paz-sh/paz-scheduler#10]
Something is written on each deploy (see resources/config/model.js#L63) but it isn't sorted in a way that's useful to be presented in a time-sorted "deployment history" interface.

Perhaps something like:

key: journal!1429102560
value: { "event": "deploy", "timestamp": 1429102560, "key": "deploy!myservice!1" }

There may be other event types that warrant journaling, hence the "type" field.

**Comment by lukebond** [comment]
I'm working on this atm

**Comment by jacyzon** [comment]
@lukebond Have you finished?

**Comment by lukebond** [comment]
I did a bunch of work on it then lost it :( you are welcome to work on this if you like @jacyzon

**Comment by jacyzon** [comment]
Too bad to hear that...
BTW, I'm working on mockup for https://github.com/paz-sh/paz-web/issues/2.
