### ISSUE TITLE
Move Dockerfile to alpine base image

### ISSUE THREAD

**Issue by lukebond** [paz-sh/paz-scheduler#15]
Because smaller

**Comment by lukebond** [comment]
@tomgco @sublimino I believe you made some progress on this recently?

See also paz-sh/paz-service-directory#5, paz-sh/paz-orchestrator#4, paz-sh/paz-haproxy#2 and paz-sh/paz-web#27

**Comment by tomgco** [comment]
@sublimino Is the man with the changes, I believe we are waiting to ensure that all of the tests pass.

**Comment by lukebond** [comment]
Fixed via 1c76d21f75122f18cd094cf9baa60477c0b26059
