### ISSUE TITLE
Is there any plans to support other schedulers?

### ISSUE THREAD

**Issue by aledbf** [paz-sh/paz-scheduler#19]

**Comment by lukebond** [comment]
Hi @aledbf! The short answer is no. Paz is currently focused on being a UI to Fleet + easy multi-host network, and hence it is tied to Fleet.

Do feel free to make a case for other schedulers, especially if you can indicate the impact it will have on the rest of Paz that is currently depending on Fleet.

**Comment by lukebond** [comment]
@aledbf going to close this, please re-open if you have some input :)
