### ISSUE TITLE
Not getting right config history for specific service

### ISSUE THREAD

**Issue by jacyzon** [paz-sh/paz-scheduler#22]
Not getting right config history for specific service

```
[GET] http://paz-scheduler.paz/config/name/history
```

see https://github.com/paz-sh/paz-scheduler/blob/5032da/resources%2Fconfig%2Fmodel.js#L92

**Comment by lukebond** [comment]
@jacyzon thanks for picking this one up! looks like you've already fixed it with #22 so not sure why this is still open, but i would like to see a test case added to guard against any other such issues before closing this one.

**Comment by lukebond** [comment]
Having just merged the PR I (somewhat embarrassedly) see why the issue wasn't closed. Nevertheless I re-open it in lieu of the above-mentioned test.

**Comment by jacyzon** [comment]
@lukebond Isn't the test case included in the PR [#23](https://github.com/paz-sh/paz-scheduler/pull/23/files#diff-698f6c5259676bbcb148b0f9eb7758daR113)  ?

**Comment by lukebond** [comment]
Indeed it is. Sorry. Too busy and not being thorough enough!
