### ISSUE TITLE
Deploy failed: spawn ENOENT

### ISSUE THREAD

**Issue by jacyzon** [paz-sh/paz-scheduler#29]
[Last Image (f553e4)](https://quay.io/repository/yldio/paz-scheduler/image/f553e4173f0f1c6dbe3c603cf9bd1a41e957dc20b02bacb07b47dd82510b9c9c) ok, but [latest image(4bf8d7)](https://quay.io/repository/yldio/paz-scheduler/image/4bf8d75034e5ad7028a49b8848a5eabd369ff1c0930cc9961167af8d6eded56f) failed.

Request:
![screenshot_2015-06-22_21-49-43](https://cloud.githubusercontent.com/assets/1522988/8283290/1853836a-1929-11e5-8b8d-1629cb26d4c0.png)

Response:

```
"spawn ENOENT"
```

Server log:

```
Jun 22 13:54:55 paz01 bash[27186]: {"name":"paz-scheduler_log","hostname":"cc81a5456b31","pid":5,"level":30,"req":{"method":"POST","url":"/hooks/deploy"},"res":{"statusCode":200,"header":""},"uuid":"3qp2n0","msg":"","time":"2015-06-22T13:54:55.778Z","src":{"file":"/usr/src/app/middleware/logger.js","line":2,"func":"module.exports"},"v":0}
Jun 22 13:54:55 paz01 bash[27186]: {"name":"paz-scheduler_log","hostname":"cc81a5456b31","pid":5,"level":30,"deploy.post":"*","uuid":"3qp2n0","msg":"","time":"2015-06-22T13:54:55.783Z","src":{"file":"/usr/src/app/hooks/deploy/controller.js","line":17,"func":"controller.post"},"v":0}
Jun 22 13:54:55 paz01 bash[27186]: {"name":"paz-scheduler_log","hostname":"cc81a5456b31","pid":5,"level":50,"err":{"message":"spawn ENOENT","name":"Error","stack":"Error: spawn ENOENT\n    at /usr/src/app/lib/deploy.js:71:19\n    at /usr/src/app/node_modules/async/lib/async.js:240:13\n    at done (/usr/src/app/node_modules/async/lib/async.js:122:15)\n    at /usr/src/app/node_modules/async/lib/async.js:25:16\n    at /usr/src/app/node_modules/async/lib/async.js:237:17\n    at /usr/src/app/node_modules/async/lib/async.js:560:34\n    at exithandler (child_process.js:644:7)\n    at ChildProcess.errorhandler (child_process.js:660:5)\n    at ChildProcess.emit (events.js:95:17)\n    at Process.ChildProcess._handle.onexit (child_process.js:808:12)"},"msg":"spawn ENOENT","time":"2015-06-22T13:54:55.870Z","src":{"file":"/usr/src/app/hooks/deploy/model.js","line":62},"v":0}
```

**Comment by sublimino** [comment]
We were out of space on the CI box. Clearing out and will re-trigger build.

**Comment by lukebond** [comment]
@sublimino we can close this now yeah?

**Comment by jacyzon** [comment]
It's not related with the CI system, I mean that it happend when I click
the deploy buttom, the scheduler just return `spawn ENOENT`, not sure what
causes that.

**Comment by sublimino** [comment]
As the integration tests are still not building correctly (due to a
fleetctl issue, haven't hacked on them for a few days) I haven't looked at
this. The CI server is back up, but it seems that wasn't the problem. I'll
have a look at the diff between github revisions of those two image hashes
when I get a mo.

**Comment by lukebond** [comment]
a fleetctl issue could explain the ENOENT issue on `spawn`. likewise, when i have time (ha!) i'll take a look.

**Comment by lukebond** [comment]
The `fleetctl` `exec` issue has also been resolved by @jacyzon's addition to the Dockerfile, but CI has had other issues (disk space previously, but also the scripts for each project configured in StriderCD are still using fig which caused a few issues such as containers not being stopped after tests and getting subsequent port clashes).

This is now resolved for paz-scheduler and it's now building. I'm now going through other Strider projects and making the same fixes.

**Comment by lukebond** [comment]
Not fixed, integration test not passing, I based my apparent success on StriderCD tests, which do in fact pass but don't highlight this issue.
