### ISSUE TITLE
When asked to deploy multiple instances, it only deploys one

### ISSUE THREAD

**Issue by lukebond** [paz-sh/paz-scheduler#31]
I think it has something to do with the way the scheduler is using `fleetctl-ssh`, ie not closing things off or handling errors or something. This is happening when I run the integration test script, which should launch 3 instance of `demo-api`, but only ever launches one.

By enabling all available debug logging for the scheduler and fleetctl I can see that fleetctl is creating the correct number of units files and writing them to disk via ssh. In the logs there are "disconnected by user" ssh messages:

```
Jun 28 13:07:19 paz-01 systemd[1]: Started OpenSSH per-connection server daemon (10.1.0.9:36081).
Jun 28 13:07:19 paz-01 systemd[1]: Starting OpenSSH per-connection server daemon (10.1.0.9:36081)...
Jun 28 13:07:19 paz-01 systemd[1]: Started OpenSSH per-connection server daemon (10.1.0.9:36082).
Jun 28 13:07:19 paz-01 systemd[1]: Starting OpenSSH per-connection server daemon (10.1.0.9:36082)...
Jun 28 13:07:19 paz-01 systemd[1]: Started OpenSSH per-connection server daemon (10.1.0.9:36083).
Jun 28 13:07:19 paz-01 systemd[1]: Starting OpenSSH per-connection server daemon (10.1.0.9:36083)...
Jun 28 13:07:19 paz-01 systemd[1]: Started OpenSSH per-connection server daemon (10.1.0.9:36084).
Jun 28 13:07:19 paz-01 systemd[1]: Starting OpenSSH per-connection server daemon (10.1.0.9:36084)...
Jun 28 13:07:19 paz-01 systemd[1]: Started OpenSSH per-connection server daemon (10.1.0.9:36085).
Jun 28 13:07:19 paz-01 systemd[1]: Starting OpenSSH per-connection server daemon (10.1.0.9:36085)...
Jun 28 13:07:20 paz-01 sshd[25672]: Accepted publickey for core from 10.1.0.9 port 36080 ssh2: RSA d3:f5:cf:99:ff:16:2b:78:9c:8e:dc:e2:14:7e:1b:d2
Jun 28 13:07:20 paz-01 sshd[25672]: Received disconnect from 10.1.0.9: 11: disconnected by user
Jun 28 13:07:20 paz-01 sshd[25684]: Accepted publickey for core from 10.1.0.9 port 36081 ssh2: RSA d3:f5:cf:99:ff:16:2b:78:9c:8e:dc:e2:14:7e:1b:d2
Jun 28 13:07:20 paz-01 sshd[25691]: Accepted publickey for core from 10.1.0.9 port 36083 ssh2: RSA d3:f5:cf:99:ff:16:2b:78:9c:8e:dc:e2:14:7e:1b:d2
Jun 28 13:07:20 paz-01 sshd[25684]: Received disconnect from 10.1.0.9: 11: disconnected by user
Jun 28 13:07:20 paz-01 sshd[25691]: Received disconnect from 10.1.0.9: 11: disconnected by user
Jun 28 13:07:20 paz-01 sshd[25685]: Accepted publickey for core from 10.1.0.9 port 36082 ssh2: RSA d3:f5:cf:99:ff:16:2b:78:9c:8e:dc:e2:14:7e:1b:d2
Jun 28 13:07:20 paz-01 sshd[25692]: Accepted publickey for core from 10.1.0.9 port 36084 ssh2: RSA d3:f5:cf:99:ff:16:2b:78:9c:8e:dc:e2:14:7e:1b:d2
Jun 28 13:07:20 paz-01 sshd[25685]: Received disconnect from 10.1.0.9: 11: disconnected by user
Jun 28 13:07:20 paz-01 sshd[25692]: Received disconnect from 10.1.0.9: 11: disconnected by user
Jun 28 13:07:20 paz-01 sshd[25697]: Accepted publickey for core from 10.1.0.9 port 36085 ssh2: RSA d3:f5:cf:99:ff:16:2b:78:9c:8e:dc:e2:14:7e:1b:d2
Jun 28 13:07:20 paz-01 bash[25050]: Sun, 28 Jun 2015 13:07:20 GMT deploy task execution complete
Jun 28 13:07:20 paz-01 bash[25050]: Sun, 28 Jun 2015 13:07:20 GMT deploy Going to insert into DB: [ { type: 'put',
Jun 28 13:07:20 paz-01 bash[25050]: key: 'journal!1435496839835',
Jun 28 13:07:20 paz-01 bash[25050]: value:
Jun 28 13:07:20 paz-01 bash[25050]: { event: 'deploy',
Jun 28 13:07:20 paz-01 bash[25050]: timestamp: 1435496839835,
Jun 28 13:07:20 paz-01 bash[25050]: key: 'deploy!demo-api!1' } },
Jun 28 13:07:20 paz-01 bash[25050]: { type: 'put',
Jun 28 13:07:20 paz-01 bash[25050]: key: 'deploy!demo-api!1',
Jun 28 13:07:20 paz-01 bash[25050]: value: { timestamp: 1435496839835, service: [Object] } },
Jun 28 13:07:20 paz-01 bash[25050]: { type: 'put', key: 'latest!demo-api', value: 1 } ]
Jun 28 13:07:20 paz-01 bash[25050]: Sun, 28 Jun 2015 13:07:20 GMT deploy DB insert okay
Jun 28 13:07:20 paz-01 bash[25050]: {"name":"paz-scheduler_log","hostname":"147de17fb545","pid":5,"level":30,"message":"Successfully deployed demo-api 
Jun 28 13:07:20 paz-01 sshd[25697]: Received disconnect from 10.1.0.9: 11: disconnected by user
```

At this stage it's a mystery and debugging it will be difficult. But it's fairly clear to me that calling of `fleetctl-ssh` via `async.parallel()` in this particular way isn't sufficient to detect errors, or perhaps it doesn't wait for completion.

@tomgco do you spot anything odd that I'm doing in the scheduler code with async [here](https://github.com/paz-sh/paz-scheduler/blob/master/lib/deploy.js#L67)? ([this](https://github.com/lukebond/fleetctl-ssh/blob/master/index.js#L23) is the fleetctl-ssh function that ultimately gets called each time).

**Comment by lukebond** [comment]
For background context, in case it's difficult to get one's head around what's going on here:

When you ask the scheduler to deploy something:
1. It fetches service info from the service-directory
2. It runs that data through `lib/unitfile` to create a pair of unit files for each instance of the service you want to deploy (one for the service, one for the announce sidekick, so for 3 instances that's 6 unit files).
3. It creates a list of functions with bound arguments that will call fleetctl-ssh for each of these unit files (i.e. 6 times in the above example).
4. It passes that list to `async.parallel`.
5. How fleetctl actually works is by ssh'ing back to the CoreOS host and running `fleetctl` commands, and it is these ssh commands that we're seeing in the logs I pasted above.

**Comment by sublimino** [comment]
This was due to the the demo-api's Fleet unit file. It had an 'X-Conflicts' directive of 

`iniObj['X-Fleet']['X-Conflicts'] = unitNameBase + '*.service''`

which meant that it was only possible to bring up a single instance of the demo-api when there is a single server to deploy to. Fixed by https://github.com/paz-sh/paz-scheduler/commit/dc96c7ad2240009553dd6253f2b37aa5b7a9dcd2
